apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels: 
    {{- include "zuul-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- include "zuul-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zuul-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.name | quote }}
          image: {{ .Values.image.repository | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetport }}
      affinity:
        {{- toYaml .Values.pa | nindent 8 }}