apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "react-ui"
  name: "ui"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: "react-ui"
  type: "NodePort"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "react-ui"
  labels:
    app: react-ui
spec:
  replicas: 1
  selector:
      matchLabels:
        app: "react-ui"
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
        - name: "react-ui"
          image: "mahendravarman12/e-commerce:ui"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: react-ui-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-ui
  minReplicas: 1
  maxReplicas: 5  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi

