---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zuul-api-gateway
  name: zuul-api-gateway
spec:
  ports:
  - name: http
    port: 9999
    targetPort: 9999
    nodePort: 32470
  type: NodePort
  selector:
    app: zuul-api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-api-gateway
  labels:
    app: zuul-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul-api-gateway
  template:
    metadata:
      labels:
        app: zuul-api-gateway
    spec:
      containers:
        - name: zuul-api-gateway
          image: mahendravarman12/e-commerce:api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
          readinessProbe:
            httpGet:
              path: /
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 9999
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zuul-api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zuul-api-gateway
  minReplicas: 1
  maxReplicas: 5  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
