---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: offer-ui
  name: offer
spec:
  ports:
  - name: http
    port: 1001
    targetPort: 1001
  selector:
    app: offer-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer-ui
  labels:
    app: offer-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer-ui
  template:
    metadata:
      labels:
        app: offer-ui
    spec:
      containers:
        - name: offer-ui
          image: mahendravarman12/e-commerce:offer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1001
          readinessProbe:
            httpGet:
              path: /
              port: 1001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 1001
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: offer-ui-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: offer-ui
  minReplicas: 1
  maxReplicas: 5  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
