---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wishlist-ui
  name: wishlist
spec:
  ports:
  - name: http
    port: 1003
    targetPort: 5000
  selector:
    app: wishlist-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-ui
  labels:
    app: wishlist-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-ui
  template:
    metadata:
      labels:
        app: wishlist-ui
    spec:
      containers:
        - name: shoe-ui
          image: mahendravarman12/e-commerce:wish
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
      readinessProbe:
        httpGet:
          path: /
          port: 5000
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 5000
        initialDelaySeconds: 10
        periodSeconds: 15
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wishlist-ui-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wishlist-ui
  minReplicas: 1
  maxReplicas: 5  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
